apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rd08bgmwy-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rd08bgmwy-python 
  name: rd08bgmwy-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: rd08bgmwy-python 
